### ISSUE TITLE
CRD validation doesn't prevent fields missing from the spec

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/apiextensions-apiserver#24]
Steps to reproduce...

Create example CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```

Create instance:

```yaml
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  name: c
spec:
  cSpec: foo
```

This is accepted, but should result in an error since there is no field cSpec
