### ISSUE TITLE
CRD validation doesn't accept empty values for type "object" fields

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/apiextensions-apiserver#25]
Create example CRD, but make spec an object

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```

Create an instance with an empty spec

```yaml
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  name: c
spec:
```

This throws the following error, but shouldn't since spec doesn't have any required fields:

> The CronTab "c" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"stable.example.com/v1", "kind":"CronTab", "metadata":map[string]interface {}{"name":"c", "namespace":"default", "creationTimestamp":"2018-02-16T15:53:27Z", "uid":"86df4c72-1331-11e8-8944-42010a800029", "selfLink":"", "clusterName":""}, "spec":interface {}(nil)}: validation failure list:

**Comment by nikhita** [comment]
@pwittrock If `spec` is defined as an **object** in the schema, for it to be empty, it can have an empty **object** value but not a **null** value i.e. the following would work:

```yaml
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  name: c
spec: {}
```

/cc @sttts

**Comment by sttts** [comment]
I agree with @pwittrock that the error is unexpect from a user point of view. Actually I am surprised that the given yaml translates to the null in JSON. Is this like that by definition of yaml?

**Comment by enisoc** [comment]
> Actually I am surprised that the given yaml translates to the null in JSON. Is this like that by definition of yaml?

Yes, I think it is:

> YAML allows the node content to be omitted in many cases. Nodes with empty content are interpreted as if they were plain scalars with an empty value. Such nodes are commonly resolved to a “null” value.

http://yaml.org/spec/1.2/spec.html#id2786563

This seems more like a YAML gotcha than a CRD validation gotcha. Although `spec` has no required fields, the provided schema says that `spec` itself is required, so `null` is invalid. If `spec` were completely optional, the schema should say it must be either `null` or an object.

**Comment by sttts** [comment]
Yes, the OpenAPI spec does not accept null for `type: object`. So the validator is correct.

One can add null to the spec though:
```yaml
openAPIV3Schema:
      properties:
        spec:
          anyOf:
          - type: "null"
          - type: object
            properties:
            ...
```
