### ISSUE TITLE
CRD validation not support enum number as expected

### ISSUE THREAD

**Issue by kindule** [kubernetes/apiextensions-apiserver#28]
Create example CRD, and validate master.replicas must be 1 or 3.

Use `Enum` not work as expected.
Always raise error `in body should be one of [1 3]`.

```Go
"master": {
    Properties: map[string]apiextensionsv1beta1.JSONSchemaProps{
        "replicas": {
            Description: "must be 1 or 3",
            Type:        "number",
            // TODO: not work as expect
            Enum: []apiextensionsv1beta1.JSON{
                {
                    Raw: []byte(fmt.Sprintf(`1`)),
                },
                {
                    Raw: []byte(fmt.Sprintf(`3`)),
                },
            },
        },
```

Use `AnyOf` can work as expected but very ugly.
```Go
"master": {
    Properties: map[string]apiextensionsv1beta1.JSONSchemaProps{
        "replicas": {
            Description: "must be 1 or 3",
            Type:        "number",
            // Work as expect but very ugly
            AnyOf: []apiextensionsv1beta1.JSONSchemaProps{
                {
                    Description: "must be 1 or 3",
                    Type:        "number",
                    Minimum:     util.Float64Ptr(1),
                    Maximum:     util.Float64Ptr(1),
                },
                {
                    Description: "must be 1 or 3",
                    Type:        "number",
                    Minimum:     util.Float64Ptr(3),
                    Maximum:     util.Float64Ptr(3),
                },
            },
        },
```

**Comment by nikhita** [comment]
@kindule Not able to reproduce this. Tried this by writing code and via kubectl as well.

**Using kubectl:**

1. Create the CRD.

```yaml
$ cat crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: number
              enum:
              - 1
              - 3
```

```sh
$ kubectl create -f crd.yaml
customresourcedefinition "crontabs.stable.example.com" created
```

2. Create an invalid custom resource.

```yaml
$ cat cr-invalid.yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 2
```

```sh
$ kubectl create -f cr-invalid.yaml
The CronTab "my-new-cron-object" is invalid: []: Invalid value: map[string]interface {}{"kind":"CronTab", "metadata":map[string]interface {}{"selfLink":"", "clusterName":"", "name":"my-new-cron-object", "namespace":"default", "generation":1, "creationTimestamp":"2018-03-12T05:42:43Z", "uid":"2f2b0c5a-25b8-11e8-a838-54e1ad6c2d05"}, "spec":map[string]interface {}{"cronSpec":"* * * * */5", "image":"my-awesome-cron-image", "replicas":2}, "apiVersion":"stable.example.com/v1"}: validation failure list:
spec.replicas in body should be one of [1 3]
```

3. Create a valid custom resource.

```yaml
$ cat cr-valid.yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 3
```

```sh
$ kubectl create -f cr-valid.yaml
crontab "my-new-cron-object" created
```

**Using code**:

I have modified one of the tests we have (https://github.com/nikhita/kubernetes/commit/086ef0d48c286992b0687db4f364ebda674f8523) and it shows validation working as expected (for enums for numbers).

Can you have a look at it? If possible, can you modify the test/let me know what needs to be changed in it to reproduce this bug?
